name: lf
channels:
  - conda-forge
dependencies:
  - llvmdev=11.1.0
  - toml
  - pytest
  - jupyter
  - xeus=5.1.0
  - xeus-zmq=3.0.0
  - xtl
  - nlohmann_json=3.12.0
  - cppzmq
  - jupyter_kernel_test
  - xonsh
  - re2c
  - numpy
  - ninja
  - m2-bison=3.0.4
  - git
  - cmake
  - zlib
