name: lf
channels:
  - conda-forge
dependencies:
  - llvmdev=11
  # Enable for OpenMP:
  #- llvm-openmp=11
  - toml
  - pytest
  - jupyter
  - xeus=3.0.5
  - xeus-zmq=1.0.2
  - xtl
  - nlohmann_json
  - cppzmq
  - jupyter_kernel_test
  - xonsh=0.16.0
  - re2c
  - numpy
  - bison=3.4
  - rapidjson
  - ninja
  - zlib
  - zstd-static
  - cmake
  - make
