name: lf
channels:
  - conda-forge
dependencies:
  - llvmdev=11
  # Enable for OpenMP:
  #- llvm-openmp=11
  - toml
  - pytest
  - jupyter
  - xeus=5.1.0
  - xeus-zmq=3.0.0
  - nlohmann_json=3.11.3
  - jupyter_kernel_test
  - xonsh=0.16.0
  - re2c
  - numpy
  - bison=3.4
  - rapidjson
  - ninja
  - zlib
  - zstd-static
  - cmake=3.29.1
  - make
  # install libunwind if building with llvmdev > 11
  # - libunwind
