name: lf
channels:
  - conda-forge
dependencies:
  - llvmdev=11
  # Enable for OpenMP:
  #- llvm-openmp=11
  - toml
  - pytest
  - jupyter
  - xeus=5.1.0
  - xeus-zmq=3.0.0
  - xtl
  - nlohmann_json
  - cppzmq
  - jupyter_kernel_test
  - xonsh
  - re2c
  - numpy
  - bison=3.4
  - rapidjson
  - ninja
  - zlib
  - zstd-static
  - cmake
  - make
