site_name: LFortran Documentation

nav:
    - Home: index.md
    - installation.md
    - language.md
    - progress.md
    - Developer's Guide:
        - design.md
        - developer_tutorial.md
        - ast_and_asr.md
        - contributing.md
    - LFortran Intrinsics:
        - Array Intrinsic Functions:
            - intrinsics/array/allocated.md
            - intrinsics/array/cshift.md
            - intrinsics/array/size.md
        - Bit Intrinsic Functions:
            - intrinsics/bit/bge.md
            - intrinsics/bit/bgt.md
            - intrinsics/bit/bit_size.md
            - intrinsics/bit/ble.md
            - intrinsics/bit/blt.md
            - intrinsics/bit/btest.md
            - intrinsics/bit/shiftl.md
            - intrinsics/bit/shiftr.md
        - Character Intrinsic Functions:
            - intrinsics/character/achar.md
            - intrinsics/character/adjustl.md
            - intrinsics/character/adjustr.md
            - intrinsics/character/char.md
            - intrinsics/character/lge.md
            - intrinsics/character/len_trim.md
        - Kind Type Intrinsic Functions:
            - intrinsics/kind-type/kind.md
        - Mathematical Intrinsic Functions:
            - intrinsics/mathematical/acos.md
            - intrinsics/mathematical/acosh.md
            - intrinsics/mathematical/asin.md
            - intrinsics/mathematical/asinh.md
            - intrinsics/mathematical/atan.md
            - intrinsics/mathematical/atan2.md
            - intrinsics/mathematical/atanh.md
            - intrinsics/mathematical/fraction.md
        - Numeric Intrinsic Functions:
            - intrinsics/numeric/abs.md
            - intrinsics/numeric/aimag.md
            - intrinsics/numeric/aint.md
            - intrinsics/numeric/anint.md
            - intrinsics/numeric/ceiling.md
            - intrinsics/numeric/cmplx.md
            - intrinsics/numeric/conjg.md
            - intrinsics/numeric/digits.md
            - intrinsics/numeric/dim.md
            - intrinsics/numeric/floor.md
            - intrinsics/numeric/mod.md
        - Miscellaneous Intrinsic Functions:
            - intrinsics/misc/command_argument_count.md
            - intrinsics/misc/cpu_time.md
            - intrinsics/misc/date_and_time.md
            - intrinsics/misc/new_line.md

# Until https://gitlab.com/lfortran/lfortran/issues/89 is fixed, we disable the
# "Edit on GitLab" link:
#repo_url: https://gitlab.com/lfortran/lfortran
#edit_uri: blob/master/doc/src

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_css:
    - ansi.css

extra_javascript:
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

theme:
    name: material
    palette:
      primary: orange
    highlightjs: true
    hljs_languages:
        - fortran

docs_dir: src
