site_name: LFortran Documentation

nav:
    - Home: index.md
    - installation.md
    - language.md
    - progress.md
    - Developer's Guide:
        - design.md
        - developer_tutorial.md
        - AST and ASR.md
        - CONTRIBUTING.md
    - LFortran Intrinsics:
        - Array Intrinsic Functions:
            - intrinsics/array/size.md
        - Bit Intrinsic Functions:
            - intrinsics/bit/shiftl.md
            - intrinsics/bit/shiftr.md
        - Character Intrinsic Functions:
            - intrinsics/character/len_trim.md
            - intrinsics/character/lge.md
        - Kind Type Intrinsic Functions:
            - intrinsics/kind-type/kind.md
        - Mathematical Intrinsic Functions:
            - intrinsics/mathematical/trigonometric/acos.md
            - intrinsics/mathematical/trigonometric/asin.md
            - intrinsics/mathematical/trigonometric/atan.md
        - Numeric Intrinsic Functions:
            - intrinsics/numeric/ceiling.md
            - intrinsics/numeric/floor.md
            - intrinsics/numeric/mod.md
        - Miscellaneous Intrinsic Functions:
            - intrinsics/misc/new_line.md

# Until https://gitlab.com/lfortran/lfortran/issues/89 is fixed, we disable the
# "Edit on GitLab" link:
#repo_url: https://gitlab.com/lfortran/lfortran
#edit_uri: blob/master/doc/src

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra_css:
    - ansi.css

theme:
    name: material
    palette:
      primary: orange
    highlightjs: true
    hljs_languages:
        - fortran

docs_dir: src
