name: lf
channels:
  - conda-forge
dependencies:
  - llvmdev=11.1.0
  - toml=0.10.2
  - pytest=8.1.1
  - jupyter=1.0.0
  - xeus=5.1.0
  - xeus-zmq=3.0.0
  - nlohmann_json=3.11.3
  - jupyter_kernel_test=0.7.0
  - re2c=3.1
  - numpy=1.26.4
  - bison=3.4
  - rapidjson=1.1.0
  - ninja=1.11.1
  - python=3.10
  - nbsphinx=0.8.9
  - myst-parser=0.18.0
  - sphinx=4.5.0
  - sphinx-copybutton=0.5.0
  - lxml=4.9.2
  - pip=23.0.1
  - unidecode=1.3.6
  - text-unidecode=1.3
  - python-slugify=8.0.1
  - cmake=3.29.1
  - pip:
    - sphinx-material==0.0.35
