name: lf
channels:
  - conda-forge
dependencies:
  - llvmdev=11.1.0
  - toml
  - pytest
  - jupyter
  - nbconvert=7.4.0
  - xeus=3.0.5
  - xeus-zmq=1.0.2
  - xtl
  - nlohmann_json=3.11.2
  - cppzmq
  - jupyter_kernel_test
  - xonsh=0.16.0
  - re2c
  - numpy
  - ninja
  - zlib
  - rapidjson
  - zstd-static=1.5.5
  - pandoc
#  - bison=3.4  [not win]
#  - m2-bison=3.4  [win]
