name: lf
channels:
  - conda-forge
dependencies:
  - llvmdev=11.1.0
  - toml=0.10.2
  - pytest=8.1.1
  - jupyter=1.0.0
  - xeus=5.1.0
  - xeus-zmq=3.0.0
  - nlohmann_json=3.11.3
  - jupyter_kernel_test=0.7.0
  - re2c=3.1
  - numpy=1.26.4
  - bison=3.4
  - rapidjson=1.1.0
  - ninja=1.11.1
  - pandoc=3.1.13
  - kokkos=4.4.01
  - cmake=3.29.1
  - zlib=1.3.1
  - zstd-static=1.5.6
  - shell=0.2.0
