name: lf
channels:
  - conda-forge
dependencies:
  - toml
  - pytest
  - jupyter
  - xeus=5.1.0
  - xeus-zmq=3.0.0
  - nlohmann_json=3.11.3
  - jupyter_kernel_test
  - xonsh=0.16.0
  - re2c
  - numpy
  - bison=3.4
  - rapidjson
  - ninja
  - zlib
